USE [master]
GO

/****** Object:  Database [Partiler]    Script Date: 31.03.2020 17:34:33 ******/
CREATE DATABASE [Partiler]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Partiler', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Partiler.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Partiler_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Partiler_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Partiler].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Partiler] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Partiler] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Partiler] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Partiler] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Partiler] SET ARITHABORT OFF 
GO

ALTER DATABASE [Partiler] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Partiler] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Partiler] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Partiler] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Partiler] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Partiler] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Partiler] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Partiler] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Partiler] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Partiler] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Partiler] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Partiler] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Partiler] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Partiler] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Partiler] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Partiler] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Partiler] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Partiler] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Partiler] SET  MULTI_USER 
GO

ALTER DATABASE [Partiler] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Partiler] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Partiler] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Partiler] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Partiler] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Partiler] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Partiler] SET  READ_WRITE 
GO

